services:
  nest-sql:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - POSTGRES_DATABASE_URL=${PG_DATABASE_URL}
      - MYSQL_DATABASE_URL=${SQL_DATABASE_URL}
    depends_on:
      - db
      - mysql
    networks:
      - app-network

  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - app-network
  # adminer:
  #   image: adminer
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pg_data:
  mysql_data:

networks:
  app-network:
